### ISSUE TITLE
Bug in term var computing for tied values

### ISSUE THREAD

**Issue by johanmazel** [mps9506/Mann-Kendall-Trend#1]
Compared to http://vsp.pnnl.gov/help/Vsample/Design_Trend_Mann_Kendall.htm, the code is adding the term for tied values instead of substracting it.
I can do a pull-request if necessary.

**Comment by mps9506** [comment]
Thanks for pointing this out! I just pushed the correction. Let me know if it causes any issues, I haven't utilized this in quite a while.

**Comment by johanmazel** [comment]
Thank you, it looks fine now.
I was actually using your code to debug an implementation in another language.
