### ISSUE TITLE
Error message about unique values

### ISSUE THREAD

**Issue by DarrenRay** [mps9506/Mann-Kendall-Trend#3]
Hi,

When running the MK function I am getting an error message on some datasets:
 test_trend,h,p,z = mk_test(ts,alpha=0.05) 
  File "C:/Python/Anaconda/SA_Water/TrendTest_rainfall_seasonal_data.py", line 107, in mk_test
    tp[i] = sum(unique_x[i] == x)
  File "C:\Python\Anaconda\lib\site-packages\pandas\core\ops.py", line 741, in wrapper
    if len(self) != len(other):
TypeError: len() of unsized object

Any ideas what this is about?

When it runs it is brilliant!!
Regards,

Darren

**Comment by DarrenRay** [comment]
I did check the var_s line. I am using:
# calculate the var(s)
    if n == g: # there is no tie
        var_s = (n*(n-1)*(2*n+5))/18
    else: # there are some ties in data
        tp = np.zeros(unique_x.shape)
        for i in range(len(unique_x)):
            tp[i] = sum(unique_x[i] == x)
        # Issue with this?? Had an original bug with + but this still throws up errors
        var_s = (n*(n-1)*(2*n+5) - np.sum(tp*(tp-1)*(2*tp+5)))/18

**Comment by mps9506** [comment]
Thanks, just pushed a fix:
```
for i in range(len(unique_x)):
            tp[i] = sum(x == unique_x[i])
```

Somehow I didn't test this on a dataset with tied values before... Sorry. Should work fine now.

**Comment by DarrenRay** [comment]
Thanks Michael. Seems to work fine now.

Darren Ray
Senior Climatologist
Bureau of Meteorology
