### ISSUE TITLE
Number of samples required to detect a trend calculation

### ISSUE THREAD

**Issue by JonnyCBB** [mps9506/Mann-Kendall-Trend#5]
Hi,

Are there any plans to implement the algorithm to calculate the number of samples required to detect a trend? As per the relevant section in [http://vsp.pnnl.gov/help/Vsample/Design_Trend_Mann_Kendall.htm](http://vsp.pnnl.gov/help/Vsample/Design_Trend_Mann_Kendall.htm). 

If not, then I'd be happy to attempt a PR.

Thanks.

**Comment by mps9506** [comment]
No plans at this time, but if you do a PR I am happy to take a look and incorporate it.

**Comment by JonnyCBB** [comment]
PR created :)
